<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.server.core</groupId>
    <artifactId>mockserver-core</artifactId>
    <name>MockServer-Core</name>
    <description>MockServer core components to create and run mock servers locally for testing</description>

    <parent>
        <groupId>com.server</groupId>
        <artifactId>mockserver</artifactId>
        <version>1.2</version>
    </parent>

    <licenses>
        <license>
            <name>MIT License</name>
            <url>https://github.com/Kazitanvirazad/mock-server/blob/master/LICENSE</url>
        </license>
    </licenses>

    <developers>
        <developer>
            <id>Kazitanvirazad</id>
            <name>Kazi Tanvir Azad</name>
            <email>tanvir.kaziazad@gmail.com</email>
            <roles>
                <role>Java Developer</role>
            </roles>
            <url>https://www.linkedin.com/in/kazitanvirazad/</url>
        </developer>
    </developers>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <release>${java.version}</release>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>${jacoco.version}</version>
                <executions>
                    <execution>
                        <id>jacoco-prepare-agent</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>jacoco-report</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                        <configuration>
                            <excludes>
                                <exclude>com/server/core/config/**</exclude>
                                <exclude>com/server/core/constants/**</exclude>
                                <exclude>com/server/core/dto/**</exclude>
                                <exclude>com/server/core/function/**</exclude>
                                <exclude>com/server/core/model/**</exclude>
                                <exclude>com/server/core/service/Service.class</exclude>
                                <exclude>com/server/core/notification/Notification.class</exclude>
                            </excludes>
                        </configuration>
                    </execution>
                    <execution>
                        <id>jacoco-check</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                        <configuration>
                            <excludes>
                                <exclude>com/server/core/config/**</exclude>
                                <exclude>com/server/core/constants/**</exclude>
                                <exclude>com/server/core/dto/**</exclude>
                                <exclude>com/server/core/function/**</exclude>
                                <exclude>com/server/core/model/**</exclude>
                                <exclude>com/server/core/service/Service.class</exclude>
                                <exclude>com/server/core/notification/Notification.class</exclude>
                            </excludes>
                            <rules>
                                <rule>
                                    <element>BUNDLE</element>
                                    <limits>
                                        <limit>
                                            <counter>LINE</counter>
                                            <value>COVEREDRATIO</value>
                                            <minimum>0.80</minimum>
                                        </limit>
                                        <limit>
                                            <counter>BRANCH</counter>
                                            <value>COVEREDRATIO</value>
                                            <minimum>0.80</minimum>
                                        </limit>
                                    </limits>
                                </rule>
                            </rules>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>